# Generated by Django 4.2.13 on 2024-07-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("attendence", "0002_attendence")]

    operations = [
        migrations.RenameField(
            model_name="attendence", old_name="operataion", new_name="operation"
        )
    ]
