# Generated by Django 4.2.13 on 2024-06-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0003_team_membership")]

    operations = [
        migrations.AlterUniqueTogether(
            name="membership", unique_together={("user", "team")}
        )
    ]
