# Generated by Django 4.2.13 on 2024-06-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0005_degree_profile_education")]

    operations = [
        migrations.AlterField(
            model_name="education", name="degree", field=models.CharField(max_length=50)
        ),
        migrations.DeleteModel(name="Degree"),
    ]
