# Generated by Django 4.2.13 on 2024-06-12 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0007_education_total_marks")]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="users.profile",
            ),
        )
    ]
