# Generated by Django 4.2.13 on 2024-06-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0010_profileimage_profile")]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beigner", "Beigner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "expert"),
                        ],
                        default="beigner",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="users.profile",
                    ),
                ),
            ],
        )
    ]
