# Generated by Django 4.2.13 on 2024-06-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0012_workingexperience_address")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(default=2, max_length=12),
            preserve_default=False,
        )
    ]
