# Generated by Django 4.2.13 on 2024-06-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0019_alter_membership_team")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("enduser", "End User"),
                    ("accountant", "Accountant"),
                    ("manager", "Manager"),
                    ("inventory_manager", "Inventory Manager"),
                    ("admin", "Admin"),
                ],
                default=("enduser", "End User"),
                max_length=30,
            ),
        )
    ]
