# Generated by Django 4.2.13 on 2024-06-25 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0021_alter_education_end_date_alter_profile_phone")]

    operations = [
        migrations.AlterField(
            model_name="profileimage",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_image",
                to="users.profile",
            ),
        )
    ]
