# Generated by Django 4.2.13 on 2024-07-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0025_alter_team_leader")]

    operations = [migrations.RemoveField(model_name="profileimage", name="title")]
