# Generated by Django 4.2.13 on 2024-07-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0026_remove_profileimage_title")]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="obtain_marks",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="education",
            name="total_marks",
            field=models.CharField(max_length=5),
        ),
    ]
