# Generated by Django 4.2.13 on 2024-07-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0029_alter_team_name")]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        )
    ]
