# Generated by Django 4.2.13 on 2024-08-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0030_alter_team_name")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("long_break", "long_break"),
                ],
                default=("enduser", "End User"),
                max_length=20,
            ),
        )
    ]
