# Generated by Django 4.2.13 on 2024-08-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0031_user_status")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("long_break", "long_break"),
                ],
                default=("active", "Active"),
                max_length=20,
            ),
        )
    ]
