# Generated by Django 4.2.13 on 2024-07-02 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_date", models.DateField(auto_now=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("casual", "Casual"),
                            ("annual", "Annual"),
                            ("medical", "Medical"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("number_of_leave_days", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=400)),
                ("attachment", models.FileField(upload_to="application_file")),
                (
                    "leave_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
