# Generated by Django 4.2.13 on 2024-07-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("leave_management", "0001_initial")]

    operations = []
