# Generated by Django 4.2.13 on 2024-07-02 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leave_management", "0002_alter_leaveapplication_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaveapplication",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("casual", "Casual"),
                    ("annual", "Annual"),
                    ("medical", "Medical"),
                ],
                default="medical",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="UserLeaves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("casual", "Casual"),
                            ("annual", "Annual"),
                            ("medical", "Medical"),
                        ],
                        default="medical",
                        max_length=8,
                    ),
                ),
                ("number_of_leaves", models.PositiveIntegerField()),
                ("remaining_leaves", models.IntegerField()),
                ("year", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
