# Generated by Django 4.2.13 on 2024-07-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("leave_management", "0002_test_empty")]

    operations = []
