# Generated by Django 4.2.13 on 2024-07-08 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leave_management", "0003_test_empty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaveapplication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_application",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
