# Generated by Django 4.2.13 on 2024-06-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="itemcategory",
            name="name",
            field=models.CharField(max_length=30),
        )
    ]
