# Generated by Django 4.2.13 on 2024-06-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0002_alter_itemcategory_name")]

    operations = [
        migrations.AlterField(
            model_name="itemcategory",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        )
    ]
