# Generated by Django 4.2.13 on 2024-06-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0003_alter_itemcategory_name")]

    operations = [
        migrations.RemoveField(model_name="useritemassignment", name="remarks"),
        migrations.AddField(
            model_name="useritemassignment",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[("in", "In"), ("out", "Out")], max_length=3
            ),
        ),
    ]
