# Generated by Django 4.2.13 on 2024-06-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0004_remove_useritemassignment_remarks_and_more")]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="quantaty", new_name="quantity"
        )
    ]
