# Generated by Django 4.2.13 on 2024-06-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0005_rename_quantaty_item_quantity")]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="quantity", new_name="remaining_quantity"
        ),
        migrations.AddField(
            model_name="item",
            name="total_quantity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
